FROM node:20-alpine


RUN apk add --no-cache openjdk21-jdk

RUN npm install -g firebase-tools

WORKDIR /app

COPY firebase.json ./
COPY .firebaserc ./
COPY dev-storage.rules ./

EXPOSE 3005 3006 9099 9199

CMD ["firebase", "emulators:start", "--only", "firestore,auth", "--project", "bp-furever"]