import { guideModel } from '../models/guideModel'
import { uploadPDF, uploadImage } from './storageService';
import admin from '../firebase'

export async function getGuide(guideID: string, firebaseCollection: string) {
    try {
        const doc = await admin.firestore().collection(firebaseCollection).doc(guideID).get();
        
        if (!doc.exists) {
            throw new Error(`Guide not found: ${guideID}`);
        }

        return doc.data()

    } catch (e){
        console.log(e)
    }
}

export async function createGuide(
  data: {
    postTitle: string;
    postSummary: string;
    imageFile: Express.Multer.File;
    pdfFile: Express.Multer.File;
  },
  firestoreCollection: string
) {
  const guideRef = admin.firestore().collection(firestoreCollection).doc();
  const guideID = guideRef.id; // autogenerated ID

  try {
    const imageLink = await uploadImage(
      data.imageFile,
      `guides/${guideID}/image`
    );

    const pdfLink = await uploadPDF(
      data.pdfFile,
      `guides/${guideID}/pdf`
    );

    const guide: guideModel = {
      guideID,
      postTitle: data.postTitle,
      postSummary: data.postSummary,
      imageLink,
      pdfLink,
    };

    await guideRef.set(guide);

    return guide;

  } catch (e) {
    console.error("Guide creation failed:", e);
    throw e;
  }
}